### ISSUE TITLE
Neutron Database Corruption on upgrade from 4.1.3 to 4.2.1

### ISSUE THREAD

**Issue by cjoelrun** [rcbops/chef-cookbooks#723]
On both centos & precise, routers can't be created post upgrade(4.1.3 to 4.2.1rc) and rpcdaemon logs show several internal server errors 

neutron server log:

```
2013-12-13 18:40:54.226 23467 TRACE neutron.api.v2.resource
2013-12-13 18:48:17.379 23467 ERROR neutron.api.v2.resource [-] index failed
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource Traceback (most recent call last):
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/api/v2/resource.py", line 84, in resource
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource     result = method(request=request, **args)
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/api/v2/base.py", line 273, in index
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource     return self._items(request, True, parent_id)
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/api/v2/base.py", line 227, in _items
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource     obj_list = obj_getter(request.context, **kwargs)
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/db/extraroute_db.py", line 167, in get_routers
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource     marker=marker, page_reverse=page_reverse)
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/db/l3_db.py", line 266, in get_routers
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource     page_reverse=page_reverse)
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/neutron/db/db_base_plugin_v2.py", line 196, in _get_collection
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource     items = [dict_func(c, fields) for c in query]
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2349, in __iter__
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource     return self._execute_and_instances(context)
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2364, in _execute_and_instances
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource     result = conn.execute(querycontext.statement, self._params)
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 662, in execute
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource     params)
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource     compiled_sql, distilled_params
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource     context)
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource     exc_info
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 195, in raise_from_cause
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource     reraise(type(exception), exception, tb=exc_tb)
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource     context)
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 324, in do_execute
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource     cursor.execute(statement, parameters)
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource     self.errorhandler(self, exc, value)
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource     raise errorclass, errorvalue
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource OperationalError: (OperationalError) (1054, "Unknown column 'routers.enable_snat' in 'field list'") 'SELECT routers.tenant_id AS routers_tenant_id, routers.id AS routers_id, routers.name AS routers_name, routers.status AS routers_status, routers.admin_state_up AS routers_admin_state_up, routers.gw_port_id AS routers_gw_port_id, routers.enable_snat AS routers_enable_snat, routerroutes_1.destination AS routerroutes_1_destination, routerroutes_1.nexthop AS routerroutes_1_nexthop, routerroutes_1.router_id AS routerroutes_1_router_id \nFROM routers LEFT OUTER JOIN routerroutes AS routerroutes_1 ON routers.id = routerroutes_1.router_id' ()
2013-12-13 18:48:17.379 23467 TRACE neutron.api.v2.resource
```

rpcdaemon log:

```
2013-12-13 10:49:59  l3agent    WARNING  Retry 10: Request Failed: internal server error while processing your request.
2013-12-13 10:50:02  l3agent    ERROR    Retries exhausted.  Exiting
2013-12-13 10:50:02  rpcdaemon  INFO     Stopping worker...
2013-12-13 10:50:07  rpcdaemon  WARNING  Error stopping worker. Shutting down uncleanly.
2013-12-13 10:50:07  rpcdaemon  INFO     Stopped.
Traceback (most recent call last):
  File "/usr/bin/rpcdaemon", line 9, in <module>
    load_entry_point('RPCDaemon==1.0.0', 'console_scripts', 'rpcdaemon')()
  File "/usr/lib/python2.6/site-packages/rpcdaemon/__init__.py", line 166, in main
    monitor.check()
  File "/usr/lib/python2.6/site-packages/rpcdaemon/__init__.py", line 145, in check
    plugin.check()
  File "/usr/lib/python2.6/site-packages/rpcdaemon/lib/neutronagent.py", line 151, in check
    self.handle(agent, False)
  File "/usr/lib/python2.6/site-packages/rpcdaemon/plugins/l3agent.py", line 90, in handle
    lambda: self.client.list_routers())['routers']
  File "/usr/lib/python2.6/site-packages/rpcdaemon/lib/neutronagent.py", line 186, in retryable
    on_fail(exc_info)
  File "/usr/lib/python2.6/site-packages/rpcdaemon/lib/neutronagent.py", line 176, in retryable
    result = fn()
  File "/usr/lib/python2.6/site-packages/rpcdaemon/plugins/l3agent.py", line 90, in <lambda>
    lambda: self.client.list_routers())['routers']
  File "/usr/lib/python2.6/site-packages/neutronclient/v2_0/client.py", line 108, in with_params
    ret = self.function(instance, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/neutronclient/v2_0/client.py", line 378, in list_routers
    **_params)
  File "/usr/lib/python2.6/site-packages/neutronclient/v2_0/client.py", line 1197, in list
    for r in self._pagination(collection, path, **params):
  File "/usr/lib/python2.6/site-packages/neutronclient/v2_0/client.py", line 1210, in _pagination
    res = self.get(path, params=params)
  File "/usr/lib/python2.6/site-packages/neutronclient/v2_0/client.py", line 1183, in get
    headers=headers, params=params)
  File "/usr/lib/python2.6/site-packages/neutronclient/v2_0/client.py", line 1168, in retry_request
    headers=headers, params=params)
  File "/usr/lib/python2.6/site-packages/neutronclient/v2_0/client.py", line 1111, in do_request
    self._handle_fault_response(status_code, replybody)
  File "/usr/lib/python2.6/site-packages/neutronclient/v2_0/client.py", line 1081, in _handle_fault_response
    exception_handler_v20(status_code, des_error_body)
  File "/usr/lib/python2.6/site-packages/neutronclient/v2_0/client.py", line 81, in exception_handler_v20
    message=error_dict)
neutronclient.common.exceptions.NeutronClientException: Request Failed: internal server error while processing your request.
2013-12-13 10:50:32  rpcdaemon  INFO     Initializing...
2013-12-13 10:50:32  rpcdaemon  INFO     Loading plugins...
2013-12-13 10:50:32  l3agent    INFO     Populating agents...
2013-12-13 10:50:32  l3agent    DEBUG    Agents: [u'7ae6efb8-9bdd-4b22-9bdd-2594d89f8063', u'7332af94-0374-422b-86fe-c782ee87ce13', u'ff9b5fcd-49ff-4032-9467-1609818fa351', u'17035e11-de59-4941-9bc5-e1661dd516e8']
2013-12-13 10:50:32  dhcpagent  INFO     Populating agents...
2013-12-13 10:50:32  dhcpagent  DEBUG    Agents: [u'1d83ae89-6d7c-4f0c-852c-8730361e66a3', u'b979fa6b-abde-4551-904e-7d1959ae4094', u'716089eb-139c-46c8-9aff-3f539df90904', u'7cdad517-acf7-4de4-942b-a1f05bf58b37']
2013-12-13 10:50:32  rpcdaemon  INFO     Starting worker...
2013-12-13 10:50:32  rpcdaemon  INFO     Started.
2013-12-13 10:50:32  rpcdaemon  DEBUG    Dispatching plugin checks...
2013-12-13 10:50:32  l3agent    DEBUG    Targets: [u'ff9b5fcd-49ff-4032-9467-1609818fa351', u'17035e11-de59-4941-9bc5-e1661dd516e8']
2013-12-13 10:50:32  l3agent    WARNING  Retry 1: Request Failed: internal server error while processing your request.
2013-12-13 10:50:35  l3agent    WARNING  Retry 2: Request Failed: internal server error while processing your request.
2013-12-13 10:50:38  l3agent    WARNING  Retry 3: Request Failed: internal server error while processing your request.
```

Creating a router:

```
[root@qa-centos-pool853 ~]# neutron router-create router1
Request Failed: internal server error while processing your request.
```

Monit status:

```
Process 'rpcdaemon'
  status                            Does not exist
  monitoring status                 Monitored
  data collected                    Fri, 13 Dec 2013 10:47:32
```

**Comment by cjoelrun** [comment]
This is the same for Precise

**Comment by cjoelrun** [comment]
rackerjoe fixed by dropping the neutron and quantum databases and rerunning chef-client. This isn't an acceptable fix and is pending further investigation

**Comment by breu** [comment]
There was already an upstream issue reported for this (https://bugs.launchpad.net/neutron/+bug/1246953).  But they could not reproduce.

**Comment by breu** [comment]
@cjoelrun I just dropped a 4.1.3 to 4.2.1rc upgrade and was not able to duplicate the neutron database upgrade problem on precise.  

```
installed 4.1.3
created a router
deleted a router
upgraded to 4.2.1rc cookbooks
chef-client

root@breu-mini-ubuntu-api1:~# neutron router-create test1
Created a new router:
+-----------------------+--------------------------------------+
| Field                 | Value                                |
+-----------------------+--------------------------------------+
| admin_state_up        | True                                 |
| external_gateway_info |                                      |
| id                    | e1c047e4-ac81-41d8-9d6f-a56f0110b7e4 |
| name                  | test1                                |
| status                | ACTIVE                               |
| tenant_id             | f77d535508df46d1b9571e5e1c37b814     |
+-----------------------+--------------------------------------+
```

I have no doubt however that it still exists for the RPM upgrades as the posttrans no doubt fails on upgrades

**Comment by breu** [comment]
I also got this on a fresh upgrade

```
oot@breu-mini-ubuntu-api1:~# monit status
The Monit daemon 5.3.2 uptime: 34m

Process 'rpcdaemon'
  status                            Running
  monitoring status                 Monitored
  pid                               27661
  parent pid                        1
  uptime                            2m
  children                          0
  memory kilobytes                  19124
  memory kilobytes total            19124
  memory percent                    0.4%
  memory percent total              0.4%
  cpu percent                       0.2%
  cpu percent total                 0.2%
  data collected                    Sat, 14 Dec 2013 15:49:30
```
